[workspace]
members = [
    "service-daemon",
    "service-daemon-macro",
    "examples/minimal",
    "examples/complete",
    "examples/triggers",
    "examples/logging",
    "examples/simulation",
    "examples/macro-tests",
    "examples/stress",
    "examples/memory-analysis",
    "examples/diagnostics",
    "examples/scheduling",
    "examples/unix-domain-socket",
    "examples/named-pipe",
    "examples/local-ipc",
    "examples/web-api",
    "examples/controller-bridge",
]
resolver = "2"
