use futures::future::BoxFuture;
use std::borrow::Cow;
use std::sync::Arc;
use tokio_util::sync::CancellationToken;

pub type ServiceFn =
    Arc<dyn Fn(CancellationToken) -> BoxFuture<'static, anyhow::Result<()>> + Send + Sync>;

/// Describes a service parameter for the registry.
///
/// The `key` field is pre-computed at compile time by the macro to avoid
/// runtime string allocations.
#[derive(Debug, Clone, Copy)]
pub struct ServiceParam {
    pub name: &'static str,
    pub type_name: &'static str,
    /// Pre-computed container key in "name_typename" format.
    pub key: &'static str,
}

impl ServiceParam {
    /// Get the container key for this parameter.
    ///
    /// This returns a pre-computed static string, avoiding allocation.
    #[inline]
    pub fn container_key(&self) -> Cow<'static, str> {
        Cow::Borrowed(self.key)
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub struct ServicePriority;

impl ServicePriority {
    /// Lowest Priority: External gateways (API, HTTP servers).
    /// Shutdown 1st, Startup Last.
    pub const EXTERNAL: u8 = 0;
    /// Middle Priority: General business logic and triggers.
    pub const DEFAULT: u8 = 50;
    /// Higher Priority: Data providers and storage managers.
    pub const STORAGE: u8 = 80;
    /// Highest Priority: Core system services (Logging, Metrics).
    /// Shutdown Last, Startup 1st.
    pub const SYSTEM: u8 = 100;
}

/// A static entry in the service registry (generated by #[service] macro)
pub struct ServiceEntry {
    pub name: &'static str,
    pub module: &'static str,
    pub params: &'static [ServiceParam],
    pub wrapper: fn(CancellationToken) -> BoxFuture<'static, anyhow::Result<()>>,
    pub watcher: Option<fn() -> BoxFuture<'static, ()>>,
    pub priority: u8,
}

/// Runtime description of a running service
pub struct ServiceDescription {
    pub name: String,
    pub run: ServiceFn,
    pub watcher: Option<Arc<dyn Fn() -> BoxFuture<'static, ()> + Send + Sync>>,
    pub priority: u8,
    pub cancellation_token: CancellationToken,
}

/// Represents the unified lifecycle status of a service.
///
/// This is the single source of truth for all service status, combining
/// both the external (daemon-observed) and internal (service-perceived) views.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ServiceStatus {
    /// The service is starting for the first time in this process session.
    Initializing,
    /// The service has been restarted after a configuration or dependency change
    /// and is ready to restore state from the shelf.
    Restoring,
    /// The service is recovering from a previous crash (panic or error).
    /// Contains the error message from the previous generation.
    Recovering(String),
    /// The service is running normally following a successful `done()` call.
    Healthy,
    /// A dependency changed; the service should save its state and call `done()`.
    NeedReload,
    /// The daemon is shutting down; the service should save its state and call `done()`.
    ShuttingDown,
    /// The service has completed its clean exit handshake and is ready for collection.
    Terminated,
}

// Define the distributed slice for automatic registration
use linkme::distributed_slice;

/// The global service registry - services register themselves here via #[service] macro
#[distributed_slice]
pub static SERVICE_REGISTRY: [ServiceEntry];
