use futures::future::BoxFuture;
use std::borrow::Cow;
use std::sync::Arc;
use tokio_util::sync::CancellationToken;

use crate::models::trigger::TriggerTemplate;

pub type ServiceFn =
    Arc<dyn Fn(CancellationToken) -> BoxFuture<'static, anyhow::Result<()>> + Send + Sync>;

/// Describes a service parameter for the registry.
///
/// The `key` field is pre-computed at compile time by the macro to avoid
/// runtime string allocations.
#[derive(Debug, Clone, Copy)]
pub struct ServiceParam {
    pub name: &'static str,
    pub type_name: &'static str,
    /// Pre-computed container key in "name_typename" format.
    pub key: &'static str,
}

impl ServiceParam {
    /// Get the container key for this parameter.
    ///
    /// This returns a pre-computed static string, avoiding allocation.
    #[inline]
    pub fn container_key(&self) -> Cow<'static, str> {
        Cow::Borrowed(self.key)
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub struct ServicePriority;

impl ServicePriority {
    /// Lowest Priority: External gateways (API, HTTP servers).
    /// Shutdown 1st, Startup Last.
    pub const EXTERNAL: u8 = 0;
    /// Middle Priority: General business logic and triggers.
    pub const DEFAULT: u8 = 50;
    /// Higher Priority: Data providers and storage managers.
    pub const STORAGE: u8 = 80;
    /// Highest Priority: Core system services (Logging, Metrics).
    /// Shutdown Last, Startup 1st.
    pub const SYSTEM: u8 = 100;
}

/// A static entry in the service registry (generated by #[service] macro)
pub struct ServiceEntry {
    pub name: &'static str,
    pub module: &'static str,
    pub params: &'static [ServiceParam],
    pub wrapper: fn(CancellationToken) -> BoxFuture<'static, anyhow::Result<()>>,
    pub priority: u8,
    /// The trigger template if this is a trigger service.
    pub template: Option<TriggerTemplate>,
}

/// Runtime description of a running service
pub struct ServiceDescription {
    pub name: String,
    pub run: ServiceFn,
    pub priority: u8,
    pub cancellation_token: CancellationToken,
}

// Define the distributed slice for automatic registration
use linkme::distributed_slice;

/// The global service registry - services register themselves here via #[service] macro
#[distributed_slice]
pub static SERVICE_REGISTRY: [ServiceEntry];
