use futures::future::BoxFuture;
use std::borrow::Cow;
use std::sync::Arc;
use tokio_util::sync::CancellationToken;

pub type ServiceFn =
    Arc<dyn Fn(CancellationToken) -> BoxFuture<'static, anyhow::Result<()>> + Send + Sync>;

/// Describes a service parameter for the registry.
///
/// The `key` field is pre-computed at compile time by the macro to avoid
/// runtime string allocations.
#[derive(Debug, Clone, Copy)]
pub struct ServiceParam {
    pub name: &'static str,
    pub type_name: &'static str,
    /// Pre-computed container key in "name_typename" format.
    pub key: &'static str,
}

impl ServiceParam {
    /// Get the container key for this parameter.
    ///
    /// This returns a pre-computed static string, avoiding allocation.
    #[inline]
    pub fn container_key(&self) -> Cow<'static, str> {
        Cow::Borrowed(self.key)
    }
}

/// A static entry in the service registry (generated by #[service] macro)
pub struct ServiceEntry {
    pub name: &'static str,
    pub module: &'static str,
    pub params: &'static [ServiceParam],
    pub wrapper: fn(CancellationToken) -> BoxFuture<'static, anyhow::Result<()>>,
}

/// Runtime description of a running service
pub struct ServiceDescription {
    pub name: String,
    pub run: ServiceFn,
}

// Define the distributed slice for automatic registration
use linkme::distributed_slice;

/// The global service registry - services register themselves here via #[service] macro
#[distributed_slice]
pub static SERVICE_REGISTRY: [ServiceEntry];
