//! Trigger models for event-driven function execution
//!
//! Triggers allow functions to be executed when specific events occur.
//!
//! **Note:** As of the unified architecture, triggers are registered directly into
//! `SERVICE_REGISTRY` as specialized services. The `TRIGGER_REGISTRY` below is kept
//! for backwards compatibility and potential migration scenarios, but is intentionally
//! empty in normal operation.

use crate::models::ServiceParam;
use futures::future::BoxFuture;
use linkme::distributed_slice;

/// A static entry in the trigger registry (generated by #[trigger] macro).
///
/// **Deprecated:** Triggers now register as services in `SERVICE_REGISTRY`.
/// This struct is kept for backwards compatibility.
#[allow(dead_code)]
pub struct TriggerEntry {
    /// Name of the trigger function
    pub name: &'static str,
    /// Template type: "custom", "notify", "event", "queue", "lb_queue", or "cron"
    pub template: &'static str,
    /// Target provider name
    pub target: &'static str,
    /// Expected type of the target provider (for verification)
    pub target_type: &'static str,
    /// Type of the payload (first parameter of the trigger function)
    pub payload_type: &'static str,
    /// Additional DI parameters (index 2+) for verification
    pub params: &'static [ServiceParam],
    /// Function that starts the trigger event loop
    pub run: fn() -> BoxFuture<'static, anyhow::Result<()>>,
}

/// The global trigger registry.
///
/// **Note:** This registry is intentionally empty. With the unified architecture,
/// triggers register themselves as specialized services in `SERVICE_REGISTRY`.
/// This distributed slice is kept for backwards compatibility.
#[distributed_slice]
pub static TRIGGER_REGISTRY: [TriggerEntry];
