//! Trigger models for event-driven function execution
//!
//! Triggers allow functions to be executed when specific events occur.

use crate::models::ServiceParam;
use futures::future::BoxFuture;
use linkme::distributed_slice;

/// A static entry in the trigger registry (generated by #[trigger] macro)
pub struct TriggerEntry {
    /// Name of the trigger function
    pub name: &'static str,
    /// Template type: "custom", "queue", or "cron"
    pub template: &'static str,
    /// Target provider name
    pub target: &'static str,
    /// Expected type of the target provider (for verification)
    pub target_type: &'static str,
    /// Type of the payload (first parameter of the trigger function)
    pub payload_type: &'static str,
    /// Additional DI parameters (index 2+) for verification
    pub params: &'static [ServiceParam],
    /// Function that starts the trigger event loop
    pub run: fn() -> BoxFuture<'static, anyhow::Result<()>>,
}

/// The global trigger registry - triggers register themselves here via #[trigger] macro
#[distributed_slice]
pub static TRIGGER_REGISTRY: [TriggerEntry];
